runtime: python39
entrypoint: gunicorn -b :8080 api_crud.wsgi

env_variables:
    DJANGO_SETTINGS_MODULE: api_crud.settings
handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
