version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    command: ["gunicorn", "--bind", "0.0.0.0:8080", "api_crud.wsgi"]
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DJANGO_SECRET_KEY=your-secret-key
      - DATABASE_URL=postgres://user:password@db:5432/dbname
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
