# Generated by Django 5.1.3 on 2024-11-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_due_date_task_data_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ordem',
            field=models.IntegerField(unique=True),
        ),
    ]
