# Generated by Django 5.1.3 on 2024-11-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ordem',
            field=models.IntegerField(),
        ),
    ]
