# Generated by Django 5.1.3 on 2024-11-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_task_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
